apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    {{- include "globex-web.argocd-syncwave" . | nindent 4 }}
  labels:
    {{- include "globex-web.labels" . | nindent 4 }}
    app.openshift.io/runtime: nodejs
  name: {{ include "globex-web.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "globex-web.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "globex-web.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "globex-web.serviceAccountName" . }}
      containers:
        - image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: {{ .Values.nodeEnv }}
            - name: PORT
              value: '{{ .Values.service.containerPort }}'
            - name: API_TRACK_USERACTIVITY
              value: {{ .Values.activityTrackingService.url }}{{ .Values.activityTrackingService.path }}
            - name: API_GET_PAGINATED_PRODUCTS
              value: {{ .Values.globexStoreApp.url }}{{ .Values.globexStoreApp.getProductsPath }}
            - name: API_GET_PRODUCT_DETAILS_BY_IDS
              value: {{ .Values.globexStoreApp.url }}{{ .Values.globexStoreApp.getProductListPath }}
            - name: API_CATALOG_RECOMMENDED_PRODUCT_IDS
              value: {{ .Values.recommendationEngine.url }}{{ .Values.recommendationEngine.path }}
            - name: API_CART_SERVICE
              value: {{ .Values.globexStoreApp.url }}{{ .Values.globexStoreApp.cartPath }}
            - name: API_CUSTOMER_SERVICE
              value: {{ .Values.globexStoreApp.url }}{{ .Values.globexStoreApp.customerPath }}
            - name: API_ORDER_SERVICE
              value: {{ .Values.globexStoreApp.url }}{{ .Values.globexStoreApp.orderPath }}
            - name: API_FETCH_PROD_REVIEWS
              value: {{ .Values.reviewService.url }}{{ .Values.reviewService.reviewPath }}
            - name: API_FETCH_PROD_REVIEWS_SUMMARY
              value: {{ .Values.reviewService.url }}{{ .Values.reviewService.summaryPath }}
            {{- if .Values.sso.enabled }}
            - name: SSO_CUSTOM_CONFIG
              value: {{ .Values.sso.client }}
            - name: SSO_AUTHORITY
              value: {{ .Values.sso.authServer }}/realms/{{ .Values.sso.realm }}
            - name: SSO_REDIRECT_LOGOUT_URI
              value: https://{{ include "globex-web.name" . }}-{{ .Release.Namespace }}.{{ .Values.subDomain }}/home
            - name: SSO_LOG_LEVEL
              value: '{{ .Values.sso.logLevel }}'
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
